// Package protocol provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package protocol

import (
	"time"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	User      MessageRole = "user"
)

// Agent defines model for Agent.
type Agent struct {
	Description *string `json:"description,omitempty"`
	Enabled     bool    `json:"enabled"`
	Name        string  `json:"name"`
	Version     string  `json:"version"`
}

// AuditEntry defines model for AuditEntry.
type AuditEntry struct {
	Id string `json:"id"`

	// Kind matches event type from agent-events.schema.json
	Kind       string    `json:"kind"`
	OccurredAt time.Time `json:"occurred_at"`

	// Payload the event JSON
	Payload map[string]interface{} `json:"payload"`
	RunId   string                 `json:"run_id"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	AgentName string `json:"agent_name"`
}

// Healthz defines model for Healthz.
type Healthz struct {
	Ok      bool    `json:"ok"`
	Version *string `json:"version,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Token JWT; also set as HttpOnly cookie aip_session
	Token string `json:"token"`
}

// Message defines model for Message.
type Message struct {
	CreatedAt time.Time   `json:"created_at"`
	Id        string      `json:"id"`
	Role      MessageRole `json:"role"`
	Text      string      `json:"text"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	Text string `json:"text"`
}

// Session defines model for Session.
type Session struct {
	AgentName string    `json:"agent_name"`
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest
