// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package protocol

import "encoding/json"
import "fmt"
import "reflect"

type Error struct {
	// Code corresponds to the JSON schema field "code".
	Code string `json:"code"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Error) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["code"]; raw != nil && !ok {
		return fmt.Errorf("field code in Error: required")
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in Error: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Error: required")
	}
	type Plain Error
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.Code) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "code", 1)
	}
	*j = Error(plain)
	return nil
}

// Opaque pass-through. Platform-specific keys go under metadata.platform; never
// expose to clients with semantic meaning.
type Metadata struct {
	// Platform corresponds to the JSON schema field "platform".
	Platform MetadataPlatform `json:"platform,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type MetadataPlatform map[string]interface{}

type RunFinished struct {
	// Reason corresponds to the JSON schema field "reason".
	Reason RunFinishedReason `json:"reason"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`
}

type RunFinishedReason string

const RunFinishedReasonDone RunFinishedReason = "done"
const RunFinishedReasonError RunFinishedReason = "error"
const RunFinishedReasonStopped RunFinishedReason = "stopped"

var enumValues_RunFinishedReason = []interface{}{
	"done",
	"stopped",
	"error",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RunFinishedReason) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RunFinishedReason {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RunFinishedReason, v)
	}
	*j = RunFinishedReason(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RunFinished) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["reason"]; raw != nil && !ok {
		return fmt.Errorf("field reason in RunFinished: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in RunFinished: required")
	}
	type Plain RunFinished
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = RunFinished(plain)
	return nil
}

type RunStarted struct {
	// Metadata corresponds to the JSON schema field "metadata".
	Metadata *Metadata `json:"metadata,omitempty"`

	// RunId corresponds to the JSON schema field "run_id".
	RunId string `json:"run_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RunStarted) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["run_id"]; raw != nil && !ok {
		return fmt.Errorf("field run_id in RunStarted: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in RunStarted: required")
	}
	type Plain RunStarted
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.RunId) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "run_id", 1)
	}
	*j = RunStarted(plain)
	return nil
}

type StateUpdate struct {
	// Key corresponds to the JSON schema field "key".
	Key string `json:"key"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// Value corresponds to the JSON schema field "value".
	Value interface{} `json:"value"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StateUpdate) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["key"]; raw != nil && !ok {
		return fmt.Errorf("field key in StateUpdate: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in StateUpdate: required")
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in StateUpdate: required")
	}
	type Plain StateUpdate
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.Key) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "key", 1)
	}
	*j = StateUpdate(plain)
	return nil
}

type TextDelta struct {
	// Text corresponds to the JSON schema field "text".
	Text string `json:"text"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TextDelta) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in TextDelta: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in TextDelta: required")
	}
	type Plain TextDelta
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TextDelta(plain)
	return nil
}

type ToolCallEnd struct {
	// CallId corresponds to the JSON schema field "call_id".
	CallId string `json:"call_id"`

	// ErrorMessage corresponds to the JSON schema field "error_message".
	ErrorMessage *string `json:"error_message,omitempty"`

	// Ok corresponds to the JSON schema field "ok".
	Ok bool `json:"ok"`

	// ResultPreview corresponds to the JSON schema field "result_preview".
	ResultPreview *string `json:"result_preview,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ToolCallEnd) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["call_id"]; raw != nil && !ok {
		return fmt.Errorf("field call_id in ToolCallEnd: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in ToolCallEnd: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ToolCallEnd: required")
	}
	type Plain ToolCallEnd
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.CallId) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "call_id", 1)
	}
	*j = ToolCallEnd(plain)
	return nil
}

type ToolCallStart struct {
	// Args corresponds to the JSON schema field "args".
	Args ToolCallStartArgs `json:"args,omitempty"`

	// CallId corresponds to the JSON schema field "call_id".
	CallId string `json:"call_id"`

	// Tool corresponds to the JSON schema field "tool".
	Tool string `json:"tool"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`
}

type ToolCallStartArgs map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ToolCallStart) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["call_id"]; raw != nil && !ok {
		return fmt.Errorf("field call_id in ToolCallStart: required")
	}
	if _, ok := raw["tool"]; raw != nil && !ok {
		return fmt.Errorf("field tool in ToolCallStart: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ToolCallStart: required")
	}
	type Plain ToolCallStart
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.CallId) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "call_id", 1)
	}
	if len(plain.Tool) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "tool", 1)
	}
	*j = ToolCallStart(plain)
	return nil
}
