#!/usr/bin/env bash
# protocols/gen-types.sh
# Regenerates types into frontend/ and backend/ from the protocol files.
# Idempotent. Invoked by `make gen`. CI uses git diff to detect drift.
set -euo pipefail

cd "$(dirname "$0")"
ROOT="$(cd .. && pwd)"

mkdir -p \
  "$ROOT/frontend/src/api" \
  "$ROOT/frontend/src/events" \
  "$ROOT/backend/internal/protocol"

echo "==> validating examples against schema"
python3 - <<'PY'
import json, sys
from pathlib import Path
import jsonschema
schema = json.load(open('agent-events.schema.json'))
jsonschema.Draft202012Validator.check_schema(schema)
v = jsonschema.Draft202012Validator(schema)
ok = True
for p in sorted(Path('examples').glob('*.json')):
    events = json.load(open(p))
    for i, ev in enumerate(events):
        for err in v.iter_errors(ev):
            print(f"{p.name}[{i}]: {err.message}"); ok = False
sys.exit(0 if ok else 1)
PY

echo "==> generating frontend TS event types from JSON Schema"
npx --yes json-schema-to-typescript@15 \
    --input agent-events.schema.json \
    --output "$ROOT/frontend/src/events/types.gen.ts" \
    --bannerComment "// GENERATED by protocols/gen-types.sh — do not edit by hand"

echo "==> generating frontend TS API types from OpenAPI"
npx --yes openapi-typescript@7 \
    openapi.yaml \
    -o "$ROOT/frontend/src/api/types.gen.ts" \
    --root-types

# Add banner to OpenAPI-generated TS (the generator doesn't take one)
{ echo "// GENERATED by protocols/gen-types.sh — do not edit by hand"; cat "$ROOT/frontend/src/api/types.gen.ts"; } > /tmp/_aip.ts && mv /tmp/_aip.ts "$ROOT/frontend/src/api/types.gen.ts"

echo "==> generating Go event structs from JSON Schema"
go run github.com/atombender/go-jsonschema@v0.18.0 \
    -p protocol \
    --tags json \
    --output "$ROOT/backend/internal/protocol/events.gen.go" \
    agent-events.schema.json

echo "==> generating Go API types from OpenAPI (types-only per ADR-0006)"
# Note: module path is github.com/oapi-codegen/oapi-codegen (renamed from
# github.com/deepmap/oapi-codegen when the project was donated to the
# oapi-codegen org). See docs/dev-environment.md.
go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.4.1 \
    -generate types \
    -package protocol \
    -o "$ROOT/backend/internal/protocol/api.gen.go" \
    openapi.yaml

echo "==> copying schema for runtime go:embed"
cp agent-events.schema.json "$ROOT/backend/internal/protocol/events.schema.embed.json"

echo "==> done"
