// GENERATED by protocols/gen-types.sh — do not edit by hand

/**
 * Canonical event envelope. Every event on the wire (Backend↔Frontend and Adapter↔Backend) is one of these. v1.
 */
export type AgentEvent = RunStarted | TextDelta | ToolCallStart | ToolCallEnd | StateUpdate | Error | RunFinished;

export interface RunStarted {
  type: "run_started";
  run_id: string;
  metadata?: Metadata;
}
/**
 * Opaque pass-through. Platform-specific keys go under metadata.platform; never expose to clients with semantic meaning.
 */
export interface Metadata {
  platform?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface TextDelta {
  type: "text_delta";
  text: string;
}
export interface ToolCallStart {
  type: "tool_call_start";
  call_id: string;
  tool: string;
  args?: {
    [k: string]: unknown;
  };
}
export interface ToolCallEnd {
  type: "tool_call_end";
  call_id: string;
  ok: boolean;
  result_preview?: string;
  error_message?: string;
}
export interface StateUpdate {
  type: "state_update";
  key: string;
  value: unknown;
}
export interface Error {
  type: "error";
  code: string;
  message: string;
}
export interface RunFinished {
  type: "run_finished";
  reason: "done" | "stopped" | "error";
}
